# Generated by Django 5.0.4 on 2024-07-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_artist', models.BooleanField(default=True)),
                ('is_editor', models.BooleanField(default=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.customuser')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            bases=('Music_Up_Dev.customuser',),
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.customuser')),
            ],
            bases=('Music_Up_Dev.customuser',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Up_Dev.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Up_Dev.artist'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('post_news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.post_news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Up_Dev.editor')),
            ],
            bases=('Music_Up_Dev.post_news',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.post_news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Up_Dev.artist')),
            ],
            bases=('Music_Up_Dev.post_news',),
        ),
    ]
