# Generated by Django 5.0.4 on 2024-08-07 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Music_Up_Dev', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_Up_Dev.album'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('post_news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.post_news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.editor')),
            ],
            bases=('Music_Up_Dev.post_news',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Music_Up_Dev.post_news')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.artist')),
            ],
            bases=('Music_Up_Dev.post_news',),
        ),
    ]
