# Generated by Django 5.0.4 on 2024-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Up_Dev', '0003_song_artist_alter_album_album_logo_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
