# Generated by Django 5.0.4 on 2024-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_Up_Dev', '0004_alter_album_album_logo_alter_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='Music_Up_Dev/media/songs/'),
        ),
    ]
